datasource:
  # 数据库链接驱动地址
  # 除非你知道自己在做什么，否则不建议更改该项
  driver: "com.mysql.cj.jdbc.Driver"
  # 数据库链接填写格式:
  #   jdbc:mysql://{数据库地址}:{数据库端口}/{使用的库名}?参数
  # 除非你知道自己在做什么，否则不建议随意更改参数
  url: "jdbc:mysql://sql.hamster3.cn:3306/Test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false"
  # 如果你不需要做多端跨服，那么请使用 sqlite 作本地数据库
  # driver: "org.sqlite.JDBC"
  # url: "jdbc:sqlite:./plugin/HamsterCore-BungeeCord/database.db"
  # 用户名
  username: "Test"
  # 密码
  password: "Test123.."
  # 最大链接数
  maximum-pool-size: 10
  # 最小链接数
  minimum-idle: 1
  # 超时回收时间
  # 单位：毫秒
  idle-timeout: 300000
  # 链接最长存活时间
  # 单位：毫秒
  # 建议设置为比数据库上的 wait_timeout 参数少 30 秒
  max-lifetime: 1800000
