datasource:
  # 数据库链接驱动地址
  # 除非你知道自己在做什么，否则不建议更改该项
  driver: "com.mysql.cj.jdbc.Driver"
  # 数据库链接填写格式:
  #   jdbc:mysql://{数据库地址}:{数据库端口}/{使用的库名}?参数
  # 除非你知道自己在做什么，否则不建议随意更改参数
  url: "jdbc:mysql://sql.hamster3.cn:3306/Test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
  # 如果你不需要做多端跨服，那么请使用 sqlite 作本地数据库
  # driver: "org.sqlite.JDBC"
  # url: "jdbc:sqlite:./plugin/HamsterCore/database.db"
  # 用户名
  username: "Test"
  # 密码
  password: "Test123.."
  # 最大链接数
  maximum-pool-size: 10
  # 最小链接数
  minimum-idle: 1
  # 连接闲置回收时间
  # 单位：毫秒
  idle-timeout: 600000
  # 链接最长存活时间
  # 单位：毫秒
  max-lifetime: 1800000
  # 验证连接存活的超时时间
  # 单位：毫秒
  validation-timeout: 5000

messages:
  COMMAND_NOT_FOUND:
    message: "§c未找到该指令！"
  COMMAND_NOT_HAS_PERMISSION:
    message: "§c你没有这个权限！"
  COMMAND_MUST_USED_BY_PLAYER:
    message: "§c这个命令只能由玩家执行！"
  COMMAND_DEBUG_INFO_MODE_ON:
    message: "§a已开启信息查询模式！"
  COMMAND_DEBUG_INFO_MODE_OFF:
    message: "§a已关闭信息查询模式！"
  COMMAND_LORE_HAND_EMPTY:
    message: "§c你必须手持一个物品才能使用这个命令！"
  COMMAND_LORE_EMPTY_INPUT:
    message: "§c你没有输入lore文本！"
  COMMAND_LORE_ADD_SUCCESS:
    message: "§a已成功添加lore文本！"
  COMMAND_LORE_CLEAR_NOTHING:
    message: "§c这个物品没有lore文本！"
  COMMAND_LORE_CLEAR_SUCCESS:
    message: "§c已清理该物品的全部lore文本！"
  COMMAND_LORE_NAME_SUCCESS:
    message: "§a已成功设置物品名称！"
  COMMAND_LORE_REMOVE_NOT_INPUT_NUMBER:
    message: "§c请输入要删除的行号！"
  COMMAND_LORE_REMOVE_INPUT_NUMBER_ERROR:
    message: "§c行号必须是一个大于0的整数！"
  COMMAND_LORE_REMOVE_INDEX_OUT_OF_RANGE:
    message: "§c你的手持物品没有这么多行lore文本！"
  COMMAND_LORE_REMOVE_SUCCESS:
    message: "§a已成功删除lore文本！"
  COMMAND_LORE_SET_NOT_INPUT_NUMBER:
    message: "§c请输入要设置的行号！"
  COMMAND_LORE_SET_INPUT_NUMBER_ERROR:
    message: "§c行号必须是一个大于0的整数！"
  COMMAND_LORE_SET_NOT_INPUT_TEXT:
    message: "§c请输入要设置的lore文本！"
  COMMAND_LORE_SET_INDEX_OUT_OF_RANGE:
    message: "§c你的手持物品没有这么多行lore文本！"
  COMMAND_LORE_SET_SUCCESS:
    message: "§a已成功设置lore文本！"
