name: HamsterCore
main: cn.hamster3.mc.plugin.core.bukkit.HamsterCorePlugin
version: ${version}
api-version: 1.13

author: MiniDay
website: https://github.com/MiniDay/hamster-core
description: 仓鼠核心：Minecraft 插件开发通用工具包

load: STARTUP

softdepend:
  - Vault
  - PlayerPoints
  - ProtocolLib

loadbefore:
  - HamsterAPI

libraries:
  - 'net.kyori:adventure-platform-bukkit:4.1.2'
  - 'com.squareup.okhttp3:okhttp:4.10.0'
  - 'com.zaxxer:HikariCP:5.0.1'

commands:
  HamsterCore:
    aliases: [ hcore, core ]
    description: 仓鼠核心调试指令
    permission: hamster.core.admin
    permission-message: §c你没有这个权限！
  lore:
    description: 仓鼠核心的 lore 修改指令
    permission: hamster.lore.admin
    permission-message: §c你没有这个权限！

permissions:
  hamster.core.admin:
    default: op
